#!/bin/bash
NAME="elasticsearch"
BIN="/usr/local/elasticsearch/bin/elasticsearch"
RETVAL=0
LOG="/Users/apple/log/init/elasticsearch.log"
start(){
	nohup $BIN &> $LOG &
	RETVAL=$?   
}

stop(){
	pkill java 
}

restart(){
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage:{start|stop|restart}"
		RETVAL=1
esac
exit $RETVAL
